name: awkward-uproot-tutorial
channels:
  - conda-forge
dependencies:
  - python>=3.12.11,<3.14
  - aiohttp>=3.12.14,<4
  - awkward>=2.8.5,<3
  - awkward-pandas>=2023.8.0,<2024
  - fsspec>=2025.7.0,<2026
  - fsspec-xrootd>=0.5.1,<0.6
  - xrootd>=5.8.1,<6
  - hist>=2.8.1,<3
  - matplotlib>=3.10.3,<4
  - mplhep>=0.4.0,<0.5
  - numba>=0.61.2,<0.62
  - numexpr>=2.10.2,<3
  - numpy>=2.2.6,<3
  - pandas>=2.3.1,<3
  - pyarrow>=20.0.0,<21
  - requests>=2.32.4,<3
  - scikit-learn>=1.7.0,<2
  - scipy>=1.16.0,<2
  - uproot>=5.6.3,<6
  - vector>=1.6.3,<2
  - particle>=0.25.4,<0.26
  - jupyterlab>=4.4.5,<5
  - jupyterlab-deck>=0.2.0,<0.3
  - jupyterlab-mathjax3>=4.3.0,<5
  - notebook>=7.4.4,<8
  - ipywidgets>=8.1.7,<9
  - root_base>=6.34.4,<7
  - c-compiler>=1.10.0,<2
  - cxx-compiler>=1.10.0,<2
  - jax>=0.7.0,<0.8
